import type { Metadata } from 'next';

import { LegalDocument } from '@/components/legal-document';
import { appConfig, legalConfig } from '@/lib/config';

export const metadata: Metadata = {
  title: `Terms of Service | ${appConfig.name}`,
  description: `The terms governing your use of ${appConfig.name}.`,
};

export default function TermsPage() {
  return (
    <LegalDocument
      title="Terms of Service"
      intro={`These Terms of Service ("Terms") govern your access to and use of ${appConfig.name} (the "Service"), operated by ${legalConfig.entity} ("we", "us", or "our"). By creating an account, generating images, or purchasing a plan, you agree to these Terms.`}
    >
      <h2>1. The Service</h2>
      <p>
        {appConfig.name} is an AI tool that generates product photography. You upload an image of a
        product, and the Service composites it into AI-generated backgrounds, lighting, and scenes
        while keeping your original product layer intact. Generated images are produced
        algorithmically and may vary in quality, accuracy, and style.
      </p>

      <h2>2. Eligibility &amp; Accounts</h2>
      <ul>
        <li>You must be at least 18 years old, or the age of majority in your jurisdiction.</li>
        <li>You are responsible for the security of your account and for all activity under it.</li>
        <li>
          You must provide accurate information and keep your contact and billing details current.
        </li>
      </ul>

      <h2>3. Credits, Plans &amp; Billing</h2>
      <p>
        The Service runs on a credit system. Free accounts receive a limited number of monthly
        credits; paid subscription plans include a larger monthly credit allowance. Subscriptions
        are billed in advance on a recurring basis through our payment processor (Creem) until
        cancelled.
      </p>
      <ul>
        <li>Credits reset or renew according to your plan and do not constitute stored cash value.</li>
        <li>
          Prices may change; we will give notice before a change affects your next billing cycle.
        </li>
        <li>
          You authorize us and our payment processor to charge your payment method for the plan you
          select, including applicable taxes.
        </li>
      </ul>
      <p>
        Cancellation and refunds are described in our{' '}
        <a href="/refund">Refund Policy</a>.
      </p>

      <h2>4. Your Content &amp; Ownership</h2>
      <p>
        You retain ownership of the product images and other materials you upload ("Input"). You
        grant us a limited license to process your Input solely to operate and provide the Service
        (for example, to remove backgrounds and generate composites). Subject to your compliance
        with these Terms and payment of applicable fees, you own the images the Service generates
        for you ("Output") to the extent permitted by law.
      </p>

      <h2>5. Your Responsibilities &amp; Acceptable Use</h2>
      <p>You represent that you have the right to upload your Input, and you agree not to:</p>
      <ul>
        <li>Upload content you do not own or have permission to use, including third-party brands, trademarks, or copyrighted material;</li>
        <li>Generate content that is unlawful, infringing, deceptive, defamatory, or that misrepresents a product;</li>
        <li>Create imagery that violates the policies of the marketplaces where you sell (e.g. Amazon, Etsy, Shopify);</li>
        <li>Reverse engineer, resell, or abuse the Service, or attempt to bypass credit limits.</li>
      </ul>
      <p>You are solely responsible for how you use Output, including in advertising and listings.</p>

      <h2>6. AI-Generated Output</h2>
      <p>
        Output is generated by automated models and is provided on an "as is" basis. We do not
        guarantee that Output will be accurate, error-free, free of artifacts, suitable for a
        particular marketplace, or that it will increase sales. See our{' '}
        <a href="/disclaimer">Disclaimer</a> for details.
      </p>

      <h2>7. Intellectual Property</h2>
      <p>
        The Service, including its software, design, and branding, is owned by {legalConfig.entity}
        and protected by intellectual property laws. These Terms do not grant you any rights to our
        trademarks or to the Service itself beyond the right to use it as permitted here.
      </p>

      <h2>8. Termination</h2>
      <p>
        You may stop using the Service and cancel your subscription at any time. We may suspend or
        terminate your access if you violate these Terms or use the Service in a way that creates
        legal or security risk. On termination, your right to use the Service ends; sections that by
        their nature should survive (such as ownership, disclaimers, and limitation of liability)
        will continue to apply.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        THE SERVICE AND ALL OUTPUT ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY
        KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, AND NON-INFRINGEMENT.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, {legalConfig.entity.toUpperCase()} WILL NOT BE LIABLE
        FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR LOST
        PROFITS OR REVENUE. OUR TOTAL LIABILITY FOR ANY CLAIM RELATING TO THE SERVICE WILL NOT EXCEED
        THE AMOUNT YOU PAID US IN THE THREE (3) MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM.
      </p>

      <h2>11. Governing Law</h2>
      <p>
        These Terms are governed by the laws of {legalConfig.governingLaw}, without regard to its
        conflict-of-laws rules. Where mandatory consumer-protection laws of your country of residence
        apply, nothing in these Terms limits the rights granted to you by those laws.
      </p>

      <h2>12. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. If we make material changes, we will update the
        "Last updated" date above and, where appropriate, notify you. Continued use of the Service
        after changes take effect constitutes acceptance.
      </p>

      <h2>13. Contact</h2>
      <p>
        Questions about these Terms? Email us at{' '}
        <a href={`mailto:${legalConfig.contactEmail}`}>{legalConfig.contactEmail}</a>.
      </p>
    </LegalDocument>
  );
}
